### ISSUE TITLE
Using DiE library in Linux

### ISSUE THREAD

**Issue by LordNoteworthy** [horsicq/die_library#1]
Hello @horsicq 

I was looking into a way to use DiE as a library, and I come across this project.

Is it limited now to Windows only ?

Cheers.

**Comment by horsicq** [comment]
Hello! 
Sure no. It should work on Linux and macOS too.

**Comment by LordNoteworthy** [comment]
I am waiting for a python binding.

some cmakefile would be great !

**Comment by calladoum-elastic** [comment]
💯 

@horsicq The CMake files would be very appreciated. I've already put together [some Python3 bindings](https://github.com/calladoum-elastic/die-python) based on the Windows pre-builds but it'd be awesome to go further and support also Linux & macOS.

**Comment by horsicq** [comment]
CMake is complete.

**Comment by horsicq** [comment]
https://github.com/elastic/die-python
