### ISSUE TITLE
Can't use lib on macOS

### ISSUE THREAD

**Issue by debxrshi** [horsicq/die_library#3]
Hi, I built the lib on macOS. Build successful. But when I try to run a program I get this error

```c
#include <stdio.h>
#include "die.h"
int main(void){
   printf("L");
}
```

```
In file included from test.c:2:
./src/include/die.h:4:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.
```

Even if I just call `die.h` I'm getting this error. Why is this happening? Why calling to `windows.h` on macOS?

Command used to compile: 
```
clang test.c -L ~/projects/die_library/tmp_build/src/dielib/  -I ~/projects/die_library/src/include 
```

Am I doing something wrong?

**Comment by horsicq** [comment]
Thanks a lot for the bugreoprt. I will fix it ASAP

**Comment by w1redch4d** [comment]
I dont see any particular winapi alternative usage in the header file so changing the following in die.h might fix
```c
#ifndef DIELIB_H
#define DIELIB_H

#ifdef _WIN32
#include <windows.h>
#endif
```
or using something similar to [die_lib.h](https://github.com/horsicq/die_library/blob/52238c1efdc56f437cc1fec0561eb5737ec167fd/src/lib/die_lib.h#L25)

in the die.h file?

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/die_library/commit/44a1d4f01a4340790744d637d093569ebf4b1e14

**Comment by w1redch4d** [comment]
@horsicq another small suggestion to consider would be a quick script to build on linux and macOS for sample.c 
for example
```bash
#!/bin/bash

FILE=/usr/lib/libdie.so
if test -f "$FILE"; then
    gcc ./simple.c -o simple -I ../../src/include/ -l:libdie.so
else
    echo "libdie.so is not installed or cannot be found in /usr/lib directory"
    echo "please run 'gcc ./simple.c -o simple -I ../../src/include/ -L<path to libdie.so> -l:libdie.so'"
    exit 1
fi
```
in linux and for macOS replacing gcc with clang and its appropriate flags should work

**Comment by horsicq** [comment]
> @horsicq another small suggestion to consider would be a quick script to build on linux and macOS for [simple.c](https://github.com/horsicq/die_library/blob/master/samples/C/simple.c) for example
> 
> ```shell
> #!/bin/bash
> 
> FILE=/usr/lib/libdie.so
> if test -f "$FILE"; then
>     gcc ./simple.c -o simple -I ../../src/include/ -l:libdie.so
> else
>     echo "libdie.so is not installed or cannot be found in /usr/lib directory"
>     echo "please run 'gcc ./simple.c -o simple -I ../../src/include/ -L<path to libdie.so> -l:libdie.so'"
>     exit 1
> fi
> ```
> 
> in linux and for macOS replacing gcc with clang and its appropriate flags should work

Thanks a lot! It will be added!
